import json
import os
from pathlib import Path
from urllib.parse import urlsplit, urlunsplit

import pytest
import allure

from ei_ui_smoke.case_data import load_smoke_case
from ei_ui_smoke.common_field_cases import (
    build_common_case_coverage,
    common_case_coverage_path,
    plan_common_field_report_items,
    save_common_case_coverage,
)
from ei_ui_smoke.allure_report import set_allure_module_metadata
from ei_ui_smoke.browser_recovery import (
    BrowserNavigationCircuit,
    BrowserNavigationCircuitOpen,
    BrowserRecoveryPolicy,
    recover_fresh_browser_session,
)
from ei_ui_smoke.failure_evidence import consume_failure_evidence
from ei_ui_smoke.qcc_browser import install_qcc_route
from ei_ui_smoke.qcc_proxy import QccSearchService, QccSettings


def pytest_addoption(parser):
    parser.addoption("--browser-smoke", action="store_true", help="run tests that access the deployed EI UI")
    parser.addoption(
        "--data-mode",
        choices=("probe", "stable", "standard"),
        default=None,
        help="test execution and data strategy",
    )
    parser.addoption(
        "--discover-common-fields",
        action="store_true",
        help="open the add form and write a runtime common-field manifest",
    )
    parser.addoption(
        "--common-cases-excel",
        default=None,
        help="Excel workbook containing the common rules on the 新增 sheet",
    )
    parser.addoption(
        "--common-cases-sheet",
        default=None,
        help="worksheet containing the common field rules",
    )
    parser.addoption(
        "--common-case-ids",
        default=None,
        help="JSON array of selected common case IDs",
    )
    parser.addoption(
        "--common-fields-manifest",
        default=None,
        help="runtime field manifest generated by --discover-common-fields",
    )
    parser.addoption(
        "--module-cases-excel",
        default=None,
        help="Excel workbook containing module-specific UI cases",
    )
    parser.addoption(
        "--module-cases-sheet",
        default=None,
        help="worksheet containing module-specific UI cases",
    )
    parser.addoption(
        "--module-case-ids",
        default=None,
        help="JSON array of selected module-specific case IDs",
    )


def pytest_generate_tests(metafunc):
    # 如果当前测试函数根本没用到 common_field_case 这个参数，直接走人，啥也不干
    if "common_field_case" not in metafunc.fixturenames:
        return
    # 1、拿配置：从命令行参数 / 环境变量，拿到Excel文件路径、清单文件、sheet页名字
    workbook = metafunc.config.getoption("--common-cases-excel") or os.getenv(
        "EI_COMMON_CASES_EXCEL", ""
    )
    manifest = metafunc.config.getoption("--common-fields-manifest") or os.getenv(
        "EI_COMMON_FIELDS_MANIFEST", ""
    )
    sheet_name = metafunc.config.getoption("--common-cases-sheet") or os.getenv(
        "EI_COMMON_CASES_SHEET", "新增"
    )
    raw_case_ids = metafunc.config.getoption("--common-case-ids") or os.getenv(
        "EI_COMMON_CASE_IDS_JSON"
    )
    selected_case_ids = None
    if raw_case_ids is not None:
        try:
            selected_case_ids = json.loads(raw_case_ids)
        except (TypeError, json.JSONDecodeError) as exc:
            raise pytest.UsageError(f"通用用例编号配置无效：{exc}") from exc
        if not isinstance(selected_case_ids, list):
            raise pytest.UsageError("通用用例编号配置必须是 JSON 数组")
    # 如果Excel路径 或者 manifest清单文件没给到
    if not workbook or not manifest:
        metafunc.parametrize(
            "common_field_case",
            [pytest.param(None, marks=pytest.mark.skip(
                reason="--common-cases-excel and --common-fields-manifest are required"
            ))],
        )
        return
    try:
        # Every selected row is visible in the report. Bound rows share a
        # physical transaction; absent controls become explicit skipped rows.
        report_items = plan_common_field_report_items(
            Path(workbook), Path(manifest), sheet_name=sheet_name,
            case_ids=selected_case_ids,
        )
        # 统计覆盖率：算出哪些规则执行了、哪些没匹配、哪些不适用，输出coverage统计
        coverage = build_common_case_coverage(
            Path(workbook), Path(manifest), sheet_name=sheet_name,
            case_ids=selected_case_ids,
        )
        # 把覆盖率统计结果写到一个json报告文件
        coverage_path = common_case_coverage_path(
            Path(manifest), sheet_name, selected_case_ids
        )
        save_common_case_coverage(coverage_path, coverage)
        # 在控制台打印一堆统计数字，方便看日志
        counts = coverage["counts"]
        print(
            "COMMON_CASE_COVERAGE "
            f"template={coverage['template_cases']} "
            f"executed_rules={counts['executed']} "
            f"bound_instances={coverage['bound_instances']} "
            f"transactions={coverage['transaction_count']} "
            f"not_applicable={counts['not_applicable']} "
            f"unsupported={counts['unsupported']} "
            f"report={coverage_path}",
            flush=True,
        )
    except (FileNotFoundError, KeyError, ValueError) as exc:
        raise pytest.UsageError(f"通用字段参数配置无效：{exc}") from exc
    if not report_items:
        metafunc.parametrize(
            "common_field_case",
            [pytest.param(None, marks=pytest.mark.skip(
                reason="Excel规则与字段清单没有可执行的匹配项"
            ))],
        )
        return
    metafunc.parametrize(
        "common_field_case",   # 和测试函数参数名完全对应，一一绑定
        report_items,          # 所有Excel有效行组成的测试数据集
        ids=[report_item.pytest_id for report_item in report_items],
    )


@pytest.hookimpl(hookwrapper=True)
def pytest_runtest_makereport(item, call):
    outcome = yield
    report = outcome.get_result()
    setattr(item, f"rep_{call.when}", report)
    if report.when != "call" or not report.failed:
        return
    page = item.funcargs.get("browser_page")
    if page is None:
        return
    try:
        evidence = consume_failure_evidence(page)
        failure_url = evidence.url if evidence is not None else page.url
        screenshot = (
            evidence.screenshot
            if evidence is not None
            else page.screenshot(full_page=True)
        )
        allure.attach(_safe_url(failure_url), "失败页面 URL", allure.attachment_type.TEXT)
        allure.attach(screenshot, "失败页面截图", allure.attachment_type.PNG)
        if evidence is not None and evidence.diagnostics:
            allure.attach(
                json.dumps(evidence.diagnostics, ensure_ascii=False, indent=2),
                "失败结构化诊断",
                allure.attachment_type.JSON,
            )
        if evidence is not None and evidence.dom_snapshot:
            allure.attach(
                json.dumps(evidence.dom_snapshot, ensure_ascii=False, indent=2),
                "失败页面 DOM 结构快照",
                allure.attachment_type.JSON,
            )
    except Exception:
        pass


def _safe_url(value: str) -> str:
    parsed = urlsplit(value)
    return urlunsplit((parsed.scheme, parsed.netloc, parsed.path, "", parsed.fragment))


@pytest.fixture(autouse=True)
def allure_module_metadata(request):
    action_case = None
    callspec = getattr(request.node, "callspec", None)
    if callspec is not None:
        candidate = callspec.params.get("action_case")
        action_case = candidate if isinstance(candidate, dict) else None
    module_id = str(
        action_case.get("module_id") if action_case else os.getenv("EI_MODULE_ID", "")
    ).strip()
    if not module_id:
        yield
        return
    action = str(
        action_case.get("action") if action_case else os.getenv("EI_ACTION", "")
    ).strip()
    if action:
        title = f"页面操作：{action}"
    else:
        title = (
            "新增保存及详情核对"
            if request.node.name == "test_configured_add_form_save_and_detail_echo"
            else "自动新增及详情核对"
        )
    set_allure_module_metadata(
        module_id=module_id,
        module_name=str(
            action_case.get("module_name") if action_case else os.getenv("EI_MODULE_NAME", "")
        ).strip() or module_id,
        form_code=str(
            action_case.get("form_code") if action_case else os.getenv("EI_FORM_CODE", "")
        ).strip(),
        test_title=title,
        sub_suite_override=os.getenv("EI_ALLURE_SUB_SUITE", ""),
    )
    yield


@pytest.fixture(scope="session")
def browser_runtime(request):
    if not request.config.getoption("--browser-smoke"):
        pytest.skip("use --browser-smoke to run deployed UI tests")
    try:
        from playwright.sync_api import sync_playwright
    except ImportError:
        pytest.skip("playwright is not installed")
    form_url = os.getenv("EI_ENTRY_URL") or os.getenv("EI_FORM_URL", "")
    if not form_url:
        form_code = os.getenv("EI_FORM_CODE", "")
        try:
            case = load_smoke_case(
                project_root=Path(__file__).resolve().parents[1],
                form_code=form_code,
            )
            form_url = case.page.form_url
        except (FileNotFoundError, ValueError):
            pytest.skip("EI_FORM_URL or a pages.json entry for EI_FORM_CODE is required")
    state = os.getenv("EI_STORAGE_STATE") or None
    with sync_playwright() as playwright:
        runtime = {"browser": None, "context": None, "page": None}
        policy = BrowserRecoveryPolicy(
            fresh_session_attempts=_positive_int_env(
                "EI_BROWSER_NAVIGATION_ATTEMPTS", 2
            ),
            circuit_failure_threshold=_positive_int_env(
                "EI_BROWSER_NAVIGATION_CIRCUIT_FAILURES", 3
            ),
        )
        circuit = BrowserNavigationCircuit(policy)

        def close_runtime_session(session=None):
            active = session if isinstance(session, dict) else runtime
            page = active.get("page")
            context = active.get("context")
            browser = active.get("browser")
            if page is not None:
                try:
                    page.close()
                except Exception:
                    pass
            if context is not None:
                try:
                    context.close()
                except Exception:
                    pass
            if browser is not None:
                try:
                    if browser.is_connected():
                        browser.close()
                except Exception:
                    pass
            if active is runtime:
                runtime.update(browser=None, context=None, page=None)

        def open_ready_session():
            session = {"browser": None, "context": None, "page": None}
            try:
                browser = playwright.chromium.launch(
                    headless=os.getenv("EI_HEADLESS", "true").lower() != "false"
                )
                context = browser.new_context(
                    storage_state=state, ignore_https_errors=True
                )
                qcc_mode = os.getenv("QCC_BROWSER_MODE", "backend").strip().lower()
                qcc_settings = (
                    QccSettings.from_env()
                    if qcc_mode == "real"
                    else QccSettings(mode=qcc_mode if qcc_mode == "mock" else "mock")
                )
                install_qcc_route(
                    context,
                    QccSearchService(qcc_settings),
                    backend_mode=qcc_mode == "backend",
                )
                page = context.new_page()
                session.update(browser=browser, context=context, page=page)
                page.goto(form_url, wait_until="domcontentloaded")
                username = os.getenv("EI_USERNAME", "")
                password = os.getenv("EI_PASSWORD", "")
                login_name = page.locator('input[name="loginName"]')
                if login_name.count() and username and password:
                    login_name.first.fill(username)
                    page.locator('input[name="password"]').first.fill(password)
                    page.locator("button.submit,button:has-text('登录')").first.click()
                    page.wait_for_load_state("networkidle")
                    page.goto(form_url, wait_until="domcontentloaded")
                page.locator("body").wait_for(state="visible", timeout=10_000)
                page.wait_for_function(
                    "() => (document.body?.innerText || '').trim().length > 0",
                    timeout=20_000,
                )
                return session
            except Exception:
                close_runtime_session(session)
                raise

        def ensure_page():
            browser = runtime["browser"]
            page = runtime["page"]
            if browser is None or not browser.is_connected() or page is None or page.is_closed():
                close_runtime_session()
                try:
                    session, attempt = recover_fresh_browser_session(
                        url=form_url,
                        policy=policy,
                        circuit=circuit,
                        open_session=open_ready_session,
                        close_session=close_runtime_session,
                    )
                except BrowserNavigationCircuitOpen as exc:
                    pytest.skip(str(exc))
                runtime.update(session)
                page = runtime["page"]
                print(
                    "BROWSER_SESSION_RECOVERED "
                    f"fresh_session_attempt={attempt} "
                    f"consecutive_item_failures={circuit.consecutive_failures}",
                    flush=True,
                )
            return page

        yield ensure_page

        close_runtime_session()


@pytest.fixture
def browser_page(browser_runtime):
    return browser_runtime()


def _positive_int_env(name: str, default: int) -> int:
    try:
        return max(1, int(os.getenv(name, str(default))))
    except ValueError:
        return default
